# -*- coding: utf-8 -*-
"""BERT_paraphrase.ipynb
Automatically generated by Colab.
"""
import pandas as pd
import torch
from torch.utils.data import TensorDataset, DataLoader
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

torch.manual_seed(42)
torch.use_deterministic_algorithms(True)

df = pd.read_csv("dataset.csv")
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

sent1 = df["sentence1"].astype(str).tolist()
sent2 = df["sentence2"].astype(str).tolist()
labels = df["label"].astype(int).tolist()

split = int(0.8 * len(df))
train_s1, test_s1 = sent1[:split], sent1[split:]
train_s2, test_s2 = sent2[:split], sent2[split:]
train_labels, test_labels = labels[:split], labels[split:]

model_name = "roberta-base"

device = "mps"
print(f"Using device: {device}")

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)
model.to(device)

train_enc = tokenizer(train_s1, train_s2, truncation=True, padding=True, max_length=128, return_tensors="pt")
test_enc  = tokenizer(test_s1,  test_s2,  truncation=True, padding=True, max_length=128, return_tensors="pt")

print('Longest sentence:', max([len(s.split()) for s in sent1 + sent2]))

dataset = TensorDataset(train_enc["input_ids"],train_enc["attention_mask"],torch.tensor(train_labels))
loader  = DataLoader(dataset, batch_size=8, shuffle=True)



optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5)

model.train()
losses = []
for epoch in range(12):
    total_loss = 0

    for input_ids, attention_mask, label in loader:
        input_ids = input_ids.to(device)
        attention_mask = attention_mask.to(device)
        label = label.to(device)
        optimizer.zero_grad()
        loss = model(input_ids=input_ids,attention_mask=attention_mask,labels=label).loss
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    avg_loss = total_loss / len(loader)
    losses.append(avg_loss)
    print(f"Epoch {epoch+1}: Loss = {avg_loss:.4f}")

plt.plot(range(1, 13), losses, marker='o')
plt.title("Training Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.savefig("loss_plot.png")
plt.close()

model.eval()
model.save_pretrained("roberta_model")
tokenizer.save_pretrained("roberta_model")
print("Starting evaluation...")

test_enc = tokenizer(test_s1, test_s2, truncation=True, padding=True, max_length=128, return_tensors="pt").to(device)

with torch.no_grad():
    preds = model(**test_enc).logits.argmax(dim=-1).cpu().tolist()

print("Accuracy:", round(accuracy_score(test_labels, preds) * 100, 2), "%")
